openapi: 3.0.0
info:
  title: Web Services - TP
  version: 1.0.0
  description: ""
servers:
  - url: "http://localhost:8082/go-api"
paths:
  /signup:
    post:
      summary: Signup
      tags:
        - Auth
      responses:
        "204":
          description: 200 - Signup
          headers:
            Date:
              schema:
                deprecated: false
          content:
            application/json:
              schema:
                type: object
        "400":
          description: 400 - Empty password
          headers:
            Date:
              schema:
                deprecated: false
            Content-Length:
              schema:
                deprecated: false
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  validationErrors:
                    type: object
                    properties:
                      password:
                        type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
  /login:
    post:
      summary: Login
      tags:
        - Auth
      responses:
        "200":
          description: 200 - Login
          headers:
            Date:
              schema:
                deprecated: false
            Content-Length:
              schema:
                deprecated: false
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "400":
          description: 400 - Empty password
          headers:
            Date:
              schema:
                deprecated: false
            Content-Length:
              schema:
                deprecated: false
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  validationErrors:
                    type: object
                    properties:
                      password:
                        type: string
        "401":
          description: 401 - Invalid credentials
          headers:
            Date:
              schema:
                type: string
            Content-Length:
              schema:
                type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
  /posts:
    post:
      summary: Create Post
      tags:
        - Posts
      responses:
        "201":
          description: 200 - Create Post
          headers:
            Date:
              schema:
                deprecated: false
            Content-Length:
              schema:
                deprecated: false
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  author:
                    type: string
                    format: email
                  content:
                    type: string
                  createdAt:
                    type: integer
                  likesCount:
                    type: integer
        "400":
          description: 400 - Invalid JSON
          headers:
            Date:
              schema:
                type: string
            Content-Length:
              schema:
                type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
    get:
      summary: List Posts
      tags:
        - Posts
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: beforeTs
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: 200 - List Posts
          headers:
            Date:
              schema:
                deprecated: false
            Content-Length:
              schema:
                deprecated: false
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    author:
                      type: string
                      format: email
                    content:
                      type: string
                    createdAt:
                      type: integer
                    likesCount:
                      type: integer
  /posts/{created-post-id}/like:
    post:
      summary: Like Post
      tags:
        - Posts
      responses:
        "200":
          description: 200 - Like Post
          headers:
            Date:
              schema:
                deprecated: false
            Content-Length:
              schema:
                deprecated: false
          content:
            application/json:
              schema:
                type: object
                properties:
                  likesCount:
                    type: integer
    parameters:
      - name: created-post-id
        in: path
        required: true
        schema:
          type: string
  /posts/{created-post-id}/unlike:
    delete:
      summary: Unlike Post
      tags:
        - Posts
      responses:
        "200":
          description: 200 - Unlike Post
          headers:
            Date:
              schema:
                deprecated: false
            Content-Length:
              schema:
                deprecated: false
          content:
            application/json:
              schema:
                type: object
                properties:
                  likesCount:
                    type: integer
    parameters:
      - name: created-post-id
        in: path
        required: true
        schema:
          type: string
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
