openapi: 3.0.0
info:
  title: Messaging API
  version: 1.0.0
  description: API de système de messagerie

servers:
  - url: http://localhost:3000

paths:
  /messages:
    get:
      tags:
        - Messages
      summary: Lister tous les messages
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [lu, non-lu]
        - name: _page
          in: query
          schema:
            type: integer
            default: 1
        - name: _limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Liste des messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"

    post:
      tags:
        - Messages
      summary: Créer un message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageInput"
      responses:
        "201":
          description: Message créé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

  /messages/{id}:
    get:
      tags:
        - Messages
      summary: Récupérer un message par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Message trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

    put:
      tags:
        - Messages
      summary: Mettre à jour un message
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [lu, non-lu]
      responses:
        "200":
          description: Message mis à jour
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

    delete:
      tags:
        - Messages
      summary: Supprimer un message
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Message supprimé

  /messages/status/unread:
    get:
      tags:
        - Messages
      summary: Compter les messages non lus
      responses:
        "200":
          description: Nombre de messages non lus
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer

  /messages/{id}/mark-as-read:
    patch:
      tags:
        - Messages
      summary: Marquer comme lu
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Message marqué comme lu
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

  /messages/{id}/mark-as-unread:
    patch:
      tags:
        - Messages
      summary: Marquer comme non lu
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Message marqué comme non lu
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

components:
  schemas:
    Message:
      type: object
      required:
        - id
        - sender
        - subject
        - content
        - status
        - createdAt
      properties:
        id:
          type: string
        sender:
          type: string
          format: email
        subject:
          type: string
        content:
          type: string
        status:
          type: string
          enum: [lu, non-lu]
        createdAt:
          type: string
          format: date-time

    MessageInput:
      type: object
      required:
        - sender
        - subject
        - content
      properties:
        sender:
          type: string
          format: email
        subject:
          type: string
        content:
          type: string
